# This file is a placeholder and should be replaced with the actual hardware configuration
# generated by running: nixos-generate-config --root /mnt
# on the target Ubuntu system after installing NixOS.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [];

  # Example placeholder configuration:
  boot.initrd.availableKernelModules = [ "sr_mod" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  swapDevices = [  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/33d4bbd6-974d-47f2-9918-36622c3ce866";  # Replace with actual UUID
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/sda1";  # Replace with actual UUID
    fsType = "vfat";
  };

  # fileSystems."/nix/store" = {
  #   device = "/dev/disk/by-uuid/";  # Replace with actual UUID
  #   fsType = "ext4";
  # };

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.hypervGuest.enable = true;
}
