# This file is a placeholder and should be replaced with the actual hardware configuration
# generated by running: nixos-generate-config --root /mnt
# on the target Ubuntu system after installing NixOS.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # PLACEHOLDER: Replace with actual hardware configuration
  # This would typically include:
  # - boot.kernelModules
  # - boot.extraModulePackages
  # - fileSystems."/" and other mount points
  # - swapDevices
  # - networking.useDHCP
  # - nixpkgs.hostPlatform

  # Example placeholder configuration:
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];  # or "kvm-amd" for AMD systems
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/PLACEHOLDER-UUID";  # Replace with actual UUID
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/PLACEHOLDER-BOOT-UUID";  # Replace with actual UUID
    fsType = "vfat";
  };

  swapDevices = [
    # { device = "/dev/disk/by-uuid/PLACEHOLDER-SWAP-UUID"; }  # Uncomment and replace if using swap
  ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
