name: "Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: cwill747-new
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#darwinConfigurations.personal-darwin.system
